config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'teddies#index'
  resources :teddies, only: [:index, :show] do
    get "like"
    get "dislike"
    member do
       get 'potential_matches'
    end
  end

  resources :matches, only: [:create]
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :item_1_id, class_name: "Teddy"
  belongs_to :item_2_id, class_name: "Teddy"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :teddy
  monetize :amount_cents
end

app/models/teddy.rb
class Teddy < ApplicationRecord
  belongs_to :category
  monetize :price_cents
  acts_as_votable
  acts_as_voter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    teddy = Teddy.find(params[:teddy_id])
      order  = Order.create!(teddy: teddy, teddy_sku: teddy.sku, amount: teddy.price, state: 'pending', user: current_user)

      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          name: teddy.sku,
          images: [teddy.photo_url],
          amount: teddy.price_cents,
          currency: 'eur',
          quantity: 1
        }],
        success_url: order_url(order),
        cancel_url: order_url(order)
      )

      order.update(checkout_session_id: session.id)
      redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/teddies_controller.rb
class TeddiesController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @teddies = Teddy.all
  end

  def show
    @teddy = Teddy.find(params[:id])
  end

  def potential_matches
    @teddy = Teddy.find(params[:id])
    @potential_matches = Teddy.where.not(id: @teddy.id).where(category: @teddy.category).where.not(id:@teddy.find_voted_items)
    raise
  end

  def like
      # see like
      @teddy_matched = Teddy.find(params[:teddy_id])
      @teddy_matching = Teddy.find(params[:teddy_matching])
      @teddy_matched.liked_by(@teddy_matching)
      @teddy_matched.save

      @is_match = false
      # Match ? / Si la personne likee a elle aussi like
      if @teddy_matched.liked? @teddy_matching
        @match = Match.new
        @match.item_1 = @teddy_matched
        @match.item_2 = @teddy_matching
        @match.save
        @is_match = true
      end

      redirect_to potential_matches_teddy_path(@teddy_matching)
    end

    def dislike
      # see dislike
      @user = User.find(params[:user_id])
      @user.disliked_by(current_user)
      @user.save
      redirect_to random_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.teddy.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Order #<%= @order.id %> <small><span class="badge badge-primary"><%= @order.state %></span></small></h1>
      <ul class="list-unstyled">
        <li><strong>ISSUED ON</strong> <%= @order.created_at.to_date %></li>
        <li><strong>TEDDY</strong> <%= @order.teddy.name %> [<%= @order.teddy_sku %>]</li>
        <li><strong>TOTAL</strong> <%= humanized_money_with_symbol @order.amount %></li>
        </li>
      </ul>
      <p>Estimated delivery in <strong>2 business days</strong></p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col-md-3"><%= image_tag @order.teddy.photo_url, width: '100%' %></div>
    <div class="col">
      <h1>Checkout summary</h1>
      <p>Purchase of <strong><%= @order.teddy.name %></strong> for <strong><%= humanized_money_with_symbol @order.amount %></strong></p>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/teddies/index.html.erb
<div class="container">
  <h1>Teddies</h1>
  <div class="row">
    <% @teddies.each do |teddy| %>
      <div class="col-6 col-md-4">
        <div class="card">
          <%= image_tag teddy.photo_url , class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= teddy.name %></h5>
            <p class="card-text"><%= teddy.category.name %></p>
            <p>Amount: <%= humanized_money_with_symbol(teddy.price) %></p>
            <%= link_to "More details", teddy_path(teddy), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/teddies/potential_matches.html.erb
<div class="container">
  <h1>Match for <%= @teddy.name %></h1>
  <div class="row">
    <% @potential_matches.each do |potential| %>
      <div class="col-6 col-md-4">
        <div class="card">
          <%= image_tag potential.photo_url , class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= potential.name %></h5>
            <p class="card-text"><%= potential.category.name %></p>
            <p>Amount: <%= humanized_money_with_symbol(potential.price) %></p>
            <%= link_to "No, thanks", teddy_dislike_path(potential), class: "btn btn-danger" %>
            <%= link_to "Like it", teddy_like_path(potential, teddy_matching: @teddy), class: "btn btn-success" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/teddies/show.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@teddy.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <h1><%= @teddy.name %></h1>
      <p>Some awesome description of our amazing teddy.</p>
      <p><%= @teddy.category.name %> </p>
      <p>Amount: <%= humanized_money_with_symbol(@teddy.price) %></p>
      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'teddy_id', @teddy.id %>
        <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
      <% end %>
      </br>
      <%= link_to "Exchange it", potential_matches_teddy_path, class: "btn btn-info" %>
    </div>
  </div>
</div>